version: 2.1
executors:
  base-node:
    docker:
      - image: poetapp/base:10.14.2-alpine

jobs:
  build:
    executor: base-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install deps
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  lint:
    executor: base-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Lint
          command: npm run lint

  package:
    executor: base-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Build dist
          command: npm run build
      - save_cache:
          key: dist-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./dist

  release:
    executor: base-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dist-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dist-v2-{{ .Branch }}-
            - dist-v2-
      - run:
          name: Semantic-release
          command: npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - package:
          requires:
            - build
      - release:
          context: semver
          requires:
            - package
          filters:
            branches:
              only: master
